### ISSUE TITLE
./QXmlEdit: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by davemSB** [lbellonda/qxmledit#34]
Dear qxmledit.

In Brief:
After I install from source I can't run QXmlEdit. I've rebooted and I continue to get a command not found error.
When I navigate to /opt/qxmledit I get the following errors
<code>
sh QXmlEdit
QXmlEdit: 2: /opt/qxmledit/./QXmlEdit: Syntax error: word unexpected (expecting ")")

./QXmlEdit
./QXmlEdit: error while loading shared libraries: libQXmlEditWidget.so.0: cannot open shared object file: No such file or directory
</code>

My system is fairly 'clean' after a recent re-install.

I got a number of errors when running make:
These where solved with the following : 
sudo apt-get install ibqt5svg5 libqt5xmlpatterns5 libqt5xmlpatterns5-dev qtxmlpatterns5-dev-tools qtxmlpatterns5-doc qtxmlpatterns5-example

I'll admit I may have gone a little wild on the xml5patterns stuff (the doc and example packages probably aren't required?).

Everything seems to be going fine, but I can't run qxmledit ? I get this error wherever I run it from.
qxmledit
qxmledit: command not found

I noticed in /opt/qxmledit/ there is a QXmlEdit file, which seems to be the executable, but I can't run this either, same error.
I've also tried as 'sudo' but no joy.
I note that there is nothing in /usr/bin or /usr/sbin have I missed something?

I had a look in the  /src/QXmlEdt.pro file and I noticed the following stanza

INST_DIR=$$(QXMLEDIT_INST_DIR)
isEmpty(INST_DIR) {
    INST_DIR = /opt/qxmledit
}

But I haven't seen anything about where the executable should be, I had a look at the desktop file and it has a simple path link to the executable.
Finaly I did a locate qxmledit, and I returned only details of the download directory, the directory I unzipped the source to, and the /opt/qxmledit directories.

I've clearly missed something.... but don't know what

Any help would be greately appreciated. Thanks

**Comment by davemSB** [comment]
Just tried opening the project in at creator, and it will run from here. So an issue with a path value somewhere possibly.

**Comment by lbellonda** [comment]
Hello, QXmlEdit needs at least the Qt packages declared in the .pro file:

xml svg network sql  xmlpatterns printsupport gui widgets core

The name of the program in the current version is "QXmlEdit", so the lowercase name is not recognized as a command. This will change for Linux programs, but now it is.

QXmlEdit loads the shared libraries installed in the same folder, so you need to write a script like this:

export LD_LIBRARY_PATH=/opt/qxmledit:$LD_LIBRARY_PATH
/opt/qxmledit/QXmlEdit

or change the installation folder to a standard one under Linux (I suppose you are using a Debian derivative).

The next version will let you choose the case of the name under Linux.

**Comment by davemSB** [comment]
Luca.

Thanks for the info.

In fact I just going the old issue #27 from the Google import.
Yes I am using Ubuntu.

I noticed a repo for qxmledit, but it hasn't been updated in quite some time. Hence the source install.

I'll make the script, how do I add a page to the wiki so as others with a similar problem can avoid it more easily (I'm new to got hub)?
Dave.

**Comment by lbellonda** [comment]
I will add a page on the wiki after the next release.
Closing this ticket.
