### ISSUE TITLE
Compilation error in openSUSE

### ISSUE THREAD

**Issue by LazyKent** [lbellonda/qxmledit#36]
I get compilation error in openSUSE Factory.
```
 data_access/sqllitegenericdata.cpp:313:28: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
  #define QRY_READ_TAGS_TYPE "select tr.objectId, t.tag from "TABLE_TAGS_RELATIONS" tr join "TABLE_GENERIC_OBJECTS" o on o.type=:type and o.id=tr.objectId join " TABLE_TAGS " t on t.id=tr.tagId "
                             ^
 data_access/sqllitegenericdata.cpp:313:81: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
  #define QRY_READ_TAGS_TYPE "select tr.objectId, t.tag from "TABLE_TAGS_RELATIONS" tr join "TABLE_GENERIC_OBJECTS" o on o.type=:type and o.id=tr.objectId join " TABLE_TAGS " t on t.id=tr.tagId "
                                                                                  ^
 data_access/sqllitegenericdata.cpp:314:35: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
  #define QRY_READ_TAGS_TYPE_AND_ID "select tr.objectId, t.tag from "TABLE_TAGS_RELATIONS" tr join "TABLE_GENERIC_OBJECTS" o on o.type=:type and o.id=tr.objectId and o.id=:id join " TABLE_TAGS " t on t.id=tr.tagId "
                                    ^
 data_access/sqllitegenericdata.cpp:314:88: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
  #define QRY_READ_TAGS_TYPE_AND_ID "select tr.objectId, t.tag from "TABLE_TAGS_RELATIONS" tr join "TABLE_GENERIC_OBJECTS" o on o.type=:type and o.id=tr.objectId and o.id=:id join " TABLE_TAGS " t on t.id=tr.tagId "
                                                                                         ^
```

**Comment by lbellonda** [comment]
Could you specify the version of the compiler and the OS? Can you paste the command line? Are the logs public?

**Comment by LazyKent** [comment]
openSUSE Factory or Tumbleweed.
It was OK before system upgrade to Qt 5.6.0. May it be related somehow?

Here is the build log:
https://build.opensuse.org/build/home:Lazy_Kent:devel/openSUSE_Tumbleweed/x86_64/qxmledit/_log

**Comment by lbellonda** [comment]
The cause of the problem is the activation of the C++11 syntax via the "-std=gnu++0x".
Can you replace the two lines that contain the error with the following ones (note the different spaces) and restart the build to test if there are other incompatibilities?
the lines are: 313, 314 of the file: src/sessions/data_access/sqllitegenericdata.cpp

#define QRY_READ_TAGS_TYPE "select tr.objectId, t.tag from " TABLE_TAGS_RELATIONS " tr join " TABLE_GENERIC_OBJECTS " o on o.type=:type and o.id=tr.objectId join " TABLE_TAGS " t on t.id=tr.tagId "
#define QRY_READ_TAGS_TYPE_AND_ID "select tr.objectId, t.tag from " TABLE_TAGS_RELATIONS " tr join " TABLE_GENERIC_OBJECTS " o on o.type=:type and o.id=tr.objectId and o.id=:id join " TABLE_TAGS " t on t.id=tr.tagId "

I have not yet a Qt 5.6 test environment.

**Comment by lbellonda** [comment]
The commit 8682e0a5d51a9c79b326fe3e1ce4d84c10653b1c on trunk compiles with gcc and c++11 enabled. 
You can test the trunk.

**Comment by LazyKent** [comment]
Compiled succeed with changes in src/sessions/data_access/sqllitegenericdata.cpp.
Thanks.

Tested the trunk and got errors `'isnan' was not declared in this scope`
The log: https://gist.github.com/LazyKent/cb9a56eef97ecbcd0ec8b2de0b24b376#file-qxmledit-build-log

**Comment by lbellonda** [comment]
I see, I need to test with the new gcc libraries to solve for the upcoming version.
What version of gcc is installed?

**Comment by LazyKent** [comment]
Installed gcc5-c++-5.3.1+r234891 and gcc-c++-5-2.50.
I don't understand, which one is in use.

**Comment by lbellonda** [comment]
defining:
export QXMLEDIT_NO_QWTPLOT=y
before invoking qmake

you should be able to disable the component that gives problems until the problem is solved.

**Comment by lbellonda** [comment]
Hello, the current version at master contains the fixes for c++11 compatibility (0.9.4).

**Comment by lbellonda** [comment]
The 0.9.4 release include the fix to this issue.
Waiting for confirmation to close the issue.

**Comment by LazyKent** [comment]
Confirmed. Fixed. Compiled in openSUSE without errors. Thanks!
Closed.
