### ISSUE TITLE
Compile : GLUT missing

### ISSUE THREAD

**Issue by MarVaneke** [lbellonda/qxmledit#38]
Hi,
My OS is Linux Mint 17.3.
I have downloaded your code and compile it, but the :
OpenGL Utility Toolkit development files (GLUT)
is missing.
I have to install :
freeglut3-dev
To help other, can you add this information to the README file or elsewhere you want.
Thanks for your app ;-)
Regards.

**Comment by lbellonda** [comment]
Published the fix.
