### ISSUE TITLE
Hard crash when trying to open XML file with weird schema and auto schema loading

### ISSUE THREAD

**Issue by jgonggrijp** [lbellonda/qxmledit#39]
I have version 0.9.6 on OS X 10.11.6. QXmlEdit crashes hard when I try open XML files with the following top-level tag while "Enable automatic loading of XML Schema associated to file edited" is enabled in the preferences:

    <alto 
        xmlns="http://www.loc.gov/standards/alto/ns-v2#" 
        xmlns:xlink="http://www.w3.org/1999/xlink" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v2# http://www.loc.gov/standards/alto/alto-v2.0.xsd"
    >

The crashes do not occur if I try to open different files or when I disable automatic Schema loading.

**Comment by lbellonda** [comment]
I found the problem, I can push a commit on a branch, if you can compile from sources, or you can wait for the next release, that is not too far.

**Comment by lbellonda** [comment]
Released 0.9.7 with a fix for this issue.
