### ISSUE TITLE
gcc 7.1 : this statement may fall through [-Werror=implicit-fallthrough=]

### ISSUE THREAD

**Issue by LW-archlinux** [lbellonda/qxmledit#41]
Arch linux switched from gcc 6.3.1 to gcc 7.1.1 .

qxmledit 0.9.7 build now fails on linux when using gcc 7.1.1 .
build log attached.

[qxmledit-0.9.7-1-x86_64-build-log.txt](https://github.com/lbellonda/qxmledit/files/1046332/qxmledit-0.9.7-1-x86_64-build-log.txt)

**Comment by lbellonda** [comment]
Hello, in the branch 0.9.7-1 a fix is committed for gcc 7.1.1.

Can you give it a try?

**Comment by LW-archlinux** [comment]
Compilation is succesfull now, and a quick testrun showed no problems.
The code looks cleaner, i think this should work fine on older pre-7 gcc also ? 

I am the maintainer for Arch Linux AUR package for your software, should I add this as a patch or do you plan on making a new release soon ?

https://aur.archlinux.org/packages/qxmledit/

**Comment by lbellonda** [comment]
I will release soon a 0.9.7-1 as source tag only after testing it on other systems and compilers.
At the end of the week, I think.
I will close the issue when releasing.

**Comment by lbellonda** [comment]
Closing this ticket with the release 0.9.7-1
