### ISSUE TITLE
Feature Request: 'View' > 'Close All' function

### ISSUE THREAD

**Issue by Eugenii10** [lbellonda/qxmledit#43]
Hello! First of all, thanks for a great app!
It would be great if you add a `'View' > 'Close All'` function (preferably with a hotkey) which will fold/collapse all nodes in the xml document (as opposed to the `View > Expanl All`). Sometimes it is easier to inspect xml document from the root. In such cases you prefer to keep the current view clear and refined as much as it is possible. So you have to perform two actions at each level/step: 1 - expand next node, 2 - close all siblings with a F12.
If we had the 'Close all' function, we would need to call it only once at the beginning, and then just expand a next node while going deeper through the document.
Thanks!

**Comment by lbellonda** [comment]
Hello, I implemented a new menu command "Close Item and Children". You can apply it to the root (as in your request) or to any other element, now in devel branch and will be inserted in next release.
At the moment there is no shortcut, maybe a shortcut will be added before next release.

**Comment by Eugenii10** [comment]
Thanks! Very nice!
