### ISSUE TITLE
Select function

### ISSUE THREAD

**Issue by Gerardg8** [lbellonda/qxmledit#44]
Hi, I'm new here and have a question

Have an xml with a lot of data.
the objects with a tag somewhere with the text 1 (a height value) can be completely removed
only with the search function I can find the branch but not select the value

select all grandchildren tag (hoogte) with a text value of 1 and mark this object in the root

can you help me?

**Comment by lbellonda** [comment]
Hello, if I undestand you problem, you can open search panel, then:
- select 'XPATH' option
- use the following expression: //*[*/text() eq '1']
- check 'selection to bookmarks'
- execute the search

the bookmarked elements can be removed using the command  in the 'Edit' menu.

You can use any XQuery expression supported by Qt version you are running.

**Comment by Gerardg8** [comment]
Hey

Thanks for your comment.
![screen shot 11-25-17 at 05 03 pm](https://user-images.githubusercontent.com/33979464/33232241-cfc5f1ba-d202-11e7-8365-6d1cb303baeb.PNG)

We have succeeded in making a selection and marking it.
But the removal must not only be this rule but the whole object
How can I do that?
Have a picture done with it, hope this is clearly visible.

With kind regards.

**Comment by lbellonda** [comment]
Hello, you should use the following settings in search. As you see, the parent of the object is selected.
You can use the menu "Edit > Delete Bookmarked items" to remove your objects. As you see, the "c" node is selected while the "d" one contains the text value.



![search](https://user-images.githubusercontent.com/11491048/33238047-c175fe02-d284-11e7-8f6e-5ef855dce3ef.png)

**Comment by Gerardg8** [comment]
Hoi,

Syntax error?
![screen shot 11-27-17 at 10 44 am](https://user-images.githubusercontent.com/33979464/33260517-5c15f760-d360-11e7-9ddf-08ce7dd61eb0.PNG)

This works almost well, the bookmark should be on the blue line.
How do I know that only "1" is selected and not "11" or "-1" and in this case only on the tag with "geostuf: relative Hoogteligging" and not another tag with the text "1"
![screen shot 11-27-17 at 10 48 am](https://user-images.githubusercontent.com/33979464/33260581-88dde942-d360-11e7-9ad9-9aad98e110fd.PNG)

Thanks again for your response and explanation

**Comment by lbellonda** [comment]
Hello, the answer to your question is to use search using a XPath. You can search and select the elements that have a child containing a text field of given name that evaluates exactly to '1'.
The XPath search exposes the XML in the editor to the evaluation of a query.

You can examine Qt documentation at this link to check what expression are supported:
http://doc.qt.io/qt-5/xquery-introduction.html

Your search probably is complicated by the different namespaces used for elements.

**Comment by lbellonda** [comment]
Hello, testing your query I found an issue, that will be fixed in the upcoming 0.9.9 release, when XML contains more than one namespace as in your image.

**Comment by Gerardg8** [comment]
Hi,

Thank you for your comment and I will wait for the next version.

**Comment by lbellonda** [comment]
Hello, version 0.9.9 is out, closing this ticket.
