### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by gazorg** [lbellonda/qxmledit#45]
The Trojan:Win32/Azden.A!cl is detected by windows defender in the QXmlEditInstaller-0.9.9.exe. It would be good with a better distributor for the binaries than Sourceforge which is not useable anymore.

**Comment by lbellonda** [comment]
Hello, did you check if the sha256 checksum corresponds with the published one in SourceForge and qxmledit.org site?
I checked the exe with some antivirus without problems.
Can you give me more details?

**Comment by gazorg** [comment]
Sorry, I deleted the file directly from windows defender and I did not
think of that. Now after downloading again I cannot recreate that and the
checksum is okay. It might be one of the other mirrors but most likely is
probably a false positive followed by updated definitions. That said
Sourceforge has bad history...

Thank you for very quick reply!

**Comment by lbellonda** [comment]
Hello, I checked online with www.virustotal.com and locally and the file is OK.
The resulting checksum is as published.
That said, what is the mirror you used? The link should be in your download manager. I will try to reproduce.

**Comment by gazorg** [comment]
I think it was the university in Kent, that file was okay now when I
checked.

// David

**Comment by lbellonda** [comment]
Hello, I verified and all seems ok.
If you agree I will close this issue.
