### ISSUE TITLE
Browse through xsd:include

### ISSUE THREAD

**Issue by skinkie** [lbellonda/qxmledit#47]
I am trying to view https://github.com/NETEx-CEN/NeTEx I would like to go to the schema in the XSD. Would it be possible to step into the next document upon an xsd:include?

**Comment by lbellonda** [comment]
Hello, speaking about the 0.9.9 version, at the moment in the XSD view ("View as XSD" button) you can include referenced schema using one of the leftmost bottom tool buttons. You can also change the visualization to "outline".

The HTML or PDF reports contain the referenced types and elements.

**Comment by skinkie** [comment]
@lbellonda thanks for your answer. In the morning I compiled the master version from Github. After opening the root document of the above github link I get an error / warning. Which after clicking OK it disappears.

```_final = readFinalAttribute(attr.value())```

I agree that the HTML report is highly attractive, it works very elegantly. After enabling outline, I do see quite something more :+1: (if I am _very_ patient, include might also work, but I am already waiting for 10 minutes ;)

What I would suggest is load includes upon unfolding a leaf (breadth first) rand not by definition depth first. That might make searching more difficult, but I doubt indexing for the search is the painful step here.

**Comment by lbellonda** [comment]
Hello, the warning is for the attribute (final) not being still managed in the viewer. You can file a bug, but it has no consequences on the program (on the user maybe yes). It will be addressed in a future release.

I am investigating the high display times, but having a full discovery solution for schemas is not optimal for my purposes. I'll try to cut times, but I do not have a date for the improvement.

**Comment by skinkie** [comment]
@lbellonda don't worry :) I am _very_ impressed by this tool already, and told my friends about this. What I noticed is that the processing is limited to a single core. I don't know if it is possible to do multithreaded processing?

**Comment by lbellonda** [comment]
Hello, I pushed an experimental branch "issue-48" (sorry for the +1 offset) that should able to handle the whole schema. You can try it, remember only that it is not fully released code, but still a work in progress.

**Comment by skinkie** [comment]
@lbellonda I would like to reopen this issue again, because I can't seem to do the trick I want. So for the same schema as mentioned above I open NeTEx_publication.xsd. I would expect I would be able to search for any Element in the XSD, for example ScheduledStopPoint. But that does not seem to be possible not even when the _Show definitions of includes_.
