### ISSUE TITLE
dyld: Library not loaded: libQXmlEditWidget.1.dylib

### ISSUE THREAD

**Issue by haloway13** [lbellonda/qxmledit#49]
Having an Issue starting QXmlEdit on Mac OSX High Sierra. Any help would be greatly appreciated. --TIm

/opt/qxmledit/QXmlEdit.app/Contents/MacOS/QXmlEdit
dyld: Library not loaded: libQXmlEditWidget.1.dylib
  Referenced from: /opt/qxmledit/QXmlEdit.app/Contents/MacOS/QXmlEdit
  Reason: image not found
Abort trap: 6

Process:               QXmlEdit [86544]
Path:                  /opt/qxmledit/QXmlEdit.app/Contents/MacOS/QXmlEdit
Identifier:            QXmlEdit
Version:               0.9.9 (0)
Code Type:             X86-64 (Native)
Parent Process:        bash [83802]
Responsible:           QXmlEdit [86544]
User ID:               504

Date/Time:             2018-05-01 21:25:05.910 -0600
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        6A433774-CCF1-B02C-7264-C3ADCB2B8090

Sleep/Wake UUID:       11A03EA9-9D48-4CC4-B4E1-5053C0D0EA18

Time Awake Since Boot: 150000 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib:

Dyld Error Message:
  Library not loaded: libQXmlEditWidget.1.dylib
  Referenced from: /opt/qxmledit/QXmlEdit.app/Contents/MacOS/QXmlEdit
  Reason: image not found

Binary Images:
       0x10d84b000 -        0x10da03fff +qxmledit.QXmlEdit (0.9.9 - 0) <FC8EC3E7-5921-35CE-8B3F-F4C8C5AC31EC> /opt/qxmledit/QXmlEdit.app/Contents/MacOS/QXmlEdit
       0x10e7c6000 -        0x10e8109df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld

Model: MacBookPro12,1, BootROM MBP121.0175.B00, 2 processors, Intel Core i5, 2.7 GHz, 16 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (X.XX.XX.XX.XXX)
Bluetooth: Version 6.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: Bluetooth USB Host Controller
USB Device: Microsoft® 2.4GHz Transceiver v8.0
USB Device: USB2.0 Hub
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by lbellonda** [comment]
Hello, you have three options:

1. Create a regular MacOSX .dmg package using the script install_scripts/macosx/installmacos-571.sh (for Qt 5.7.1, you have maybe to adapt it for different Qt versions).

2. Add the location of the libraries to the dynamic libraries search path via the varialble DYLD_LIBRARY_PATH.

3. Use one of the prebuilt .dmg images in the download section of qxmledit.org site.

If you want to compile yourself QXmlEdit, my advice is to follow the solution 1 (native dmg package). Maybe you will have to tweak the script, but you will end with a regular MacOSX application.

What Qt version are you using?

**Comment by lbellonda** [comment]
Add this line in your profile script:

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:##NEWPATH##
replace ##NEWPATH## with the path to libQXmlEditWidget.1.dylib, but, please, consider creating the dmg image, this is the way to install applications under MacOS.

**Comment by lbellonda** [comment]
Hello, may I close this ticket?

**Comment by lbellonda** [comment]
Closing this ticket after one month.
