### ISSUE TITLE
Edit inner XML is not working

### ISSUE THREAD

**Issue by gmarkko** [lbellonda/qxmledit#51]
I select xml element and choose "Edit inner XML..." from the context menu. The error message displaying "Data empty. Unable to load." pops out. Using the latest Version 0.9.10

**Comment by lbellonda** [comment]
Hello, the message is exaggerated and will be removed in the next release. It is only a warning for an empty field.
You can dismiss the message and continue the editing.
If you edit an element with existing nested XML, the message will not show anymore.

**Comment by gmarkko** [comment]
yes, I am editing a non empty xml element with the child elements inside.
However, warning is displayed and the empty edit windows opens. I would
expect that it is possible to modify the content inside the selected tag in
a free text mode.

On Jul 3, 2018 19:15, "Luca Bellonda" <notifications@github.com> wrote:

Hello, the message is exaggerated and will be removed in the next release.
It is only a warning for an empty field.
You can dismiss the message and continue the editing.
If you edit an element with existing nested XML, the message will not show
anymore.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lbellonda/qxmledit/issues/51#issuecomment-402212731>,
or mute the thread

**Comment by lbellonda** [comment]
Sorry for the misunderstanding, but the “Edit inner XML” feature is for editing a text node as a string with XML syntax to embed an XML in a text node.
You can edit only one element at time as text (using the shortcut ‘e’) or using a form (with double click).
It is possible to edit the text of an element (using 't' or with double click) but it is not possible to edit a hierarchy of nodes as free text.

**Comment by lbellonda** [comment]
Hello, the wrong message has been fixed on 0.9.11.

Closing this ticket.
