### ISSUE TITLE
Anonymize --> exception for attributes: xpath exepression for selecting all attributes doesn't work

### ISSUE THREAD

**Issue by aikyde** [lbellonda/qxmledit#53]
Please see files screens/attached: anonymization exceptions for all attributes named "description" are not applied

![image](https://user-images.githubusercontent.com/36932957/48219711-3ea2e180-e39e-11e8-8d97-e84c69dd1e1f.png)

![image](https://user-images.githubusercontent.com/36932957/48219736-537f7500-e39e-11e8-869c-ec393ccbd2d5.png)

**Comment by aikyde** [comment]
[food_example.ZIP](https://github.com/lbellonda/qxmledit/files/2563086/food_example.ZIP)

**Comment by aikyde** [comment]
[food_example.ZIP](https://github.com/lbellonda/qxmledit/files/2563091/food_example.ZIP)

**Comment by lbellonda** [comment]
Sorry, the documentation is not exact, the Path field is not supporting a full XPath, but a XPath syntax with explicit element path.

If you add exception for attributes using the UI, you will find that the exception data are using the full path of the element. At the moment only full paths are supported. It will be better to call it simply a "Path" as in the column title of the exception list.

Anyway in the attached sample there is no "description" attribute.

**Comment by aikyde** [comment]
Oops.. you're right, sorry for the wrong example file(

And thank you for clarifying this quickly! It would be nice to get a full XPath support someday since it could potentially save a lot of efforts when configuring profiles... :)

Anyway thank you for the great tool!

**Comment by lbellonda** [comment]
>> It would be nice to get a full XPath support someday 

It would be nice, but with full paths it is simpler to use streaming to process very huge files without memory problems. The UI is used to create profiles to be executed in batch (Tools/Anonymize File).
