### ISSUE TITLE
(K)Ububtu, Debian: module qt*-scxml is not available

### ISSUE THREAD

**Issue by hhrhhr** [lbellonda/qxmledit#55]
https://packages.ubuntu.com/scxml - not found
https://packages.debian.org/scxml - not found

Is it possible to build a program using only distribution libraries?

**Comment by lbellonda** [comment]
Can you include a log of a build under ubuntu?

**Comment by hhrhhr** [comment]
Ubuntu — 5.11.1 (https://packages.ubuntu.com/search?suite=cosmic&keywords=libqt5)
Debian — 5.7.1 (https://packages.debian.org/search?suite=stretch&keywords=libqt5)

Compilation log, unfortunately, I did not save. But it was a standard qmake error about the missing module.

I had to install Qt through an online installer. It took 2 GB, which I think is quite a lot for one editor. Maybe make using the _scxml_ module optional?

**Comment by lbellonda** [comment]
Good point. Scheduled for next release. Leaving the ticket open until the task is complete.

**Comment by lbellonda** [comment]
Hello, the current "devel" branch supports optionally SCXML even using Qt5.
Could you test it on your environment? Details in the INSTALL file in the root folder.

Best regards.

**Comment by hhrhhr** [comment]
In a couple of days, be sure to check, thanks.

**Comment by lbellonda** [comment]
Glad to hear it. May I close the ticket?

**Comment by lbellonda** [comment]
Closing this ticket.
