### ISSUE TITLE
Searching by XPath doesn't work

### ISSUE THREAD

**Issue by reavertm** [lbellonda/qxmledit#56]
The same query works well in 'xmlint -xpath' on the same XML file, while in QXmlEdit it always fails with:

"No variable with name root. exists
: location: 1-33 http://www.w3.org/2005/xqt-errors#XPST0008"

I think QXmlEdit should define/provide all the namespaces so that search by xpath "just works".

**Comment by lbellonda** [comment]
Hello, I need the data to verify the problem.

**Comment by franga2000** [comment]
I just ran into this issue on this file: [int_promet_bus_postaje(1).xml.txt](https://github.com/lbellonda/qxmledit/files/10343564/int_promet_bus_postaje.1.xml.txt)

Using v1.9.17, any query starting with `.//` (for example `.//public:int_promet_bus_postaje`) fails with:
![image](https://user-images.githubusercontent.com/3891092/210542989-1f8aa608-8b0c-4c65-8d5e-62941dfa1027.png)
and
![image](https://user-images.githubusercontent.com/3891092/210543021-e044807c-2326-4319-a635-0c7ffd383801.png)

The same query works using `lxml` (Python) and http://xpather.com/

**Comment by lbellonda** [comment]
The dot is not interpreted as expression, but as part of the name of an internal variable. Since the root of the XML is already pointing to the current context, at the moment you can leave out the '.' while I am working on this.

**Comment by lbellonda** [comment]
released
