### ISSUE TITLE
Turn over QXmlEdit Snap tomaintainers or Snapcrafters

### ISSUE THREAD

**Issue by frederickjh** [lbellonda/qxmledit#57]
@lbellonda I am now to the point of working on turning over the snap over to someone else to maintain. I started the process of turning it over to the Snapcrafters, they suggested that since I had already made contact with you that I should contact you first to see if you and the other QXmlEdit maintainers want to take it over ownership and maintain the QXmlEdit snap. I have one [issue](https://github.com/frederickjh/qxmledit/issues/5) that was suggested that I want to see if I can take care of before I would turn it over unless you want to do it.

**Comment by frederickjh** [comment]
One other thing, I got an email today from Snapcraft that I thought you might be interested in.

![image](https://user-images.githubusercontent.com/864159/50181469-c5879a00-030c-11e9-944b-5896a1c3fecd.png)

**Comment by lbellonda** [comment]
Hello, unfortunately I have nor the time, nor the experience to become the maintainer of the Snapcraft package. However I can surely answer to questions related to QXmlEdit if needed.
You can post a message about this on the QXmlEdit mailing list.

Best regards.

**Comment by frederickjh** [comment]
@lbellonda Thanks for the quick reply. Then I will turn the snap over to Snapcrafters.

One other thing before I turn the snap over to the Snapcrafters, I still need help from you to be able to fix the documentation button that does not work.

See this [comment](https://github.com/lbellonda/qxmledit/issues/50#issuecomment-416860958) about it. Here is the important part that I need your help with to fix this:

> From other examples I need to be able to set the path to the directory that QXmlEdit looks to find the file at to $SNAP/opt/qxmledit. If you look at my snapcraft.yaml (and also the qxmledit.desktop file) you will see this is what I did so that the .desktop file could find the icon. I believe that the $SNAP variable will be set at runtime so that the path to the document file will be correct.

> **Can you add a qmake option to allow setting where QXmlEdit will look for the documentation file? It means that QXmlEdit will need to get the $SNAP environment variable at runtime?**

Thanks again for your time and help!
Frederick

**Comment by Lin-Buo-Ren** [comment]
> However I can surely answer to questions related to QXmlEdit if needed.

I would like to ask if QXmlEdit has any kind of network access, this will determine whether we should allow the snap package to access it.

**Comment by frederickjh** [comment]
> I would like to ask if QXmlEdit has any kind of network access, this will determine whether we should allow the snap package to access it.

@Lin-Buo-Ren I do not think so, but I will let @lbellonda give the definitive answer.

**Comment by lbellonda** [comment]
> I would like to ask if QXmlEdit has any kind of network access, this will determine whether we should allow the snap package to access it.

Brief: yes

the only network access needed is for downloading the XSD referenced in the XML files when using one of the validation options. It is a minor option, with a workaround (copying locally the needed files).

Best regards.

**Comment by frederickjh** [comment]
@Lin-Buo-Ren I am closing this issue as @lbellonda the maintainer of QXmlEdit has declined to take over maintainership of the QXmlEdit snap.

**Comment by frederickjh** [comment]
@lbellonda Just wanted to let you know that after some changes  with a lot of help from @Lin-Buo-Ren we have released the newest builds of QXmlEdit (version 0.9.12) on the beta channel in the Snap Store. It is read to test and the issue with the documentation has also been fixed.
