### ISSUE TITLE
Add QXmlEdit snap information to qxmledit.org/info.html

### ISSUE THREAD

**Issue by frederickjh** [lbellonda/qxmledit#59]
@lbellonda I did not find a repository for the QXmlEdit website so I could submit a pull request for this, so I am opening an issue to have this added to the website.

I just released the QXmlEdit snap on the stable release channel. Quite some time has gone by without any negative feedback.

At this point it would be good if instructions on how to install the QXmlEdit snap could be added to the [Info and Downloads](http://qxmledit.org/info.html) page.

I have included a suggested text below.

Frederick

----

QXmlEdit can also be installed as a snap. Snaps are app packages for desktop, cloud and IoT that are easy to install, secure, cross-platform and dependency-free. Snaps are used by millions of people across 41 Linux distributions.

To install the QXmlEdit snap: 
`sudo snap install qxmledit`
More information about snaps can be found in the [Snapcraft Getting Started Documentation](https://docs.snapcraft.io/getting-started/3876).

**Comment by frederickjh** [comment]
This may be more concise than what I wrote for more information, but you can decide.

([Don't have snapd installed?](https://snapcraft.io/docs/core/install))

**Comment by frederickjh** [comment]
**Email from:** help@snapcraft.io

----

![image](https://user-images.githubusercontent.com/864159/53099952-2870f980-3527-11e9-8efa-ddcbbad21235.png)

**Comment by frederickjh** [comment]
Under the publicise page for QXmlEdit there are two "Get it from the Snap Store" logos with the html code that can be used to promote the QXmlEdit snap. One in black and one is white. I post it here in case you would like to use one of them.

<a href="https://snapcraft.io/qxmledit">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

```
<a href="https://snapcraft.io/qxmledit">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>
```

HTML:
<a href="https://snapcraft.io/qxmledit">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-white.svg" />
</a>

```
HTML:
<a href="https://snapcraft.io/qxmledit">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-white.svg" />
</a>
```

**Comment by lbellonda** [comment]
Hello, I will insert the information on the site in some format, but as policy I do not directly endorse external built binaries unless I am accountable for them.

**Comment by frederickjh** [comment]
Thanks @lbellonda ! As you know you can take over the building of the snap any time you want. Once you accept the pull request, I have submitted, to add the snapcraft.yaml file this repository would be ready to do so. We just need to have them transfer ownership.

**Comment by frederickjh** [comment]
The number of people installing QXmlEdit via the snap is going up steadily since it has been released in the stable channel.  The report from December 18. 2018 showed only 218 total installs and that was when the snap was only in the edge and beta channels, which means people had to search harder to find it.

![image](https://user-images.githubusercontent.com/864159/54548396-1e1c1100-49a8-11e9-9cc5-027230ad7633.png)

**Comment by frederickjh** [comment]
![image](https://user-images.githubusercontent.com/864159/56318713-062edd00-6160-11e9-9416-978807442736.png)

Not sure how 108 **Weekly active devices** is more than 134. At least that is what I believe the green and the upward arrow are suppose to mean.

**Comment by lbellonda** [comment]
Added a reference in the "news" page.

**Comment by frederickjh** [comment]
It would still be nice to see it listed in the downloads section, even if you put some kind of disclaimer on it.

**Comment by frederickjh** [comment]
@lbellonda the QXmlEdit snap has passed 1000 users recently in under a years time that it has been available even though it is not liste on QXmlEdits download page.
![image](https://user-images.githubusercontent.com/864159/64591036-2e3a0980-d3a9-11e9-8bf1-d3dbbbedc915.png)

And that in over 82 Teritories. The top ones with the most users (+30) are:
Germany           130
United States    111
Russia                 88
France                 68
United Kingdom 57
Italy                     56
Brazil                   45
Poland                42
Netherlands        40
Spain                   38
India                    36
![image](https://user-images.githubusercontent.com/864159/64591207-8ec94680-d3a9-11e9-8874-b8c780d8394f.png)

I also want to point out that on [QXmlEdit News page](http://qxmledit.org/news.html) you have listed the Snapcraft team as maintaining the QXmlEdit snap. I had some help from one of the Snapcraft team in the final stages before releasing on the stable channel but I am not on the Snapcraft team and when I asked them to take over maintaining the snap, they declined.

Lately the maintenance has mostly consisted of getting an email from Snap Store like this:
> A scan of this snap shows that it was built with packages from the Ubuntu
archive that have since received security updates. The following lists new USNs
for affected binary packages in each snap revision:

`<snip>`

> Simply rebuilding the snap will pull in the new security updates and resolve
this. If your snap also contains vendored code, now might be a good time to
review it for any needed updates.
>
>Thank you for your snap and for attending to this matter.
Logging into build.snapcraft.io, click the "Build Manually Now" button, waiting until all architectures have built then go to the releases page and promote the new versions from the edge channel to the beta, candidate and stable channels.

I know in the past both you and the Snapcraft team have declined to take over maintaining the QXmlEdit snap, however I think that it would be better if someone that really cares about the project would take over maintaining the snap. Currently it is low maintenance, however this could change with the release of a new version of QXmlEdit and I may at that point in time decide to not continue working on it.

I have posted an [issue](https://github.com/frederickjh/qxmledit/issues/16) on the Github project for the snap saying that I am looking for a new maintainer. I wanted to let you know first in case you may have changed your mind about taking over maintaining the QXmlEdit snap.

I am once again at a point of major change in my life. I will be away from home for the months of October and November and during that period I cannot promise I will be able to devote much, if any time to maintaining the QXmlEdit snap.

**Comment by frederickjh** [comment]
Now getting close to 1500 snap users of QXmlEdit. In the last week the majority of users have upgraded from the stable version 0.9.13 to 0.9.15, as we did not have a stable release of 0.9.14 as a snap.

![image](https://user-images.githubusercontent.com/864159/76834341-4e052b00-682d-11ea-9c07-c30da53fda46.png)

**Comment by frederickjh** [comment]
We have now past 1700 users, with over 1500 on the newest version of QXmlEdit.

![image](https://user-images.githubusercontent.com/864159/97430911-d5656180-1919-11eb-9919-562e19172f69.png)

**Comment by frederickjh** [comment]
I am closing this as **will not fix**.
I find his all very sad. I worked on this originally for my own use at work. That work need no longer exists. Snapcrafters refused to take over maintainership as did @lbellonda.

You refuse to even recognize the packaging by mentioning it on the downloads page. Despite all this the snap is now approaching 1900 users.

![image](https://user-images.githubusercontent.com/864159/101148078-8055f300-361d-11eb-9adf-4500fd776bc2.png)


I am still looking for a maintainer to take over this project. I plan to move literally halfway around the world. In this new location my connection to the internet may not be the best and I will no longer have time to do the regular updates for security updates in packages included in this snap.

I plan to ask Snapcrafters again to take over the project next year before I move. If no one steps up I will be forced to I archive the Github repo and remove the QXmlEdit snap from the snap store. It would be a security risk to leave it as it is with no one to do the builds and releases when security updates to packages included in the QXmlEdit snap come out.

If someone see this and is interested to maintain the snap of QXmlEdit respond to [this issue](https://github.com/frederickjh/qxmledit/issues/16) on the QXmlEdit snap project.
