### ISSUE TITLE
Build fails with Qt 5.13

### ISSUE THREAD

**Issue by luigino** [lbellonda/qxmledit#62]
See [build log](https://github.com/lbellonda/qxmledit/files/3418461/qxmledit.log).

**Comment by lbellonda** [comment]
Hello, to compile you can disable the option to transform warnings into errors commenting the following lines in the .pro files until the problem is solved.
#QMAKE_CXXFLAGS += -Wall
#QMAKE_CXXFLAGS +=-Werror

**Comment by david-geiger** [comment]
Same issue here on Mageia Cauldron with Qt 5.13.

**Comment by lbellonda** [comment]
Fix commited on devel branch.

**Comment by coevolving** [comment]
Will this be soon moved beyond development branch?  Wondering at https://aur.archlinux.org/packages/qxmledit/#comment-720175 .

**Comment by lbellonda** [comment]
Version 0.9.14 is due before the end of this month. It will contain this fix.

**Comment by lbellonda** [comment]
@coevolving : do you mind to test compile the "devel" branch? It is the base for the next release and some new branches have been merged in.

**Comment by coevolving** [comment]
@lbellonda Sorry, I'm just leaving for a family vacation, and should be offline for a while.

I've posted your request to @Lone_Wolf over at https://aur.archlinux.org/packages/qxmledit/#comment-721020 .  Let's see if he can help.

**Comment by lbellonda** [comment]
Thank you anyway. Have a nice holiday.

**Comment by LW-archlinux** [comment]
here you go, lbellonda . no build failures.

build recipe https://app.box.com/s/chpqv7covhco77dc7hnztaptyw7kpufq
log of build() function https://app.box.com/s/gev2bt2hz13frtrcwwdvrd1d05kuvd85
package() function output https://app.box.com/s/wufzlhefo5e0lwkfh7fenxv0egksn6z5

**Comment by LW-archlinux** [comment]
Archlinux updated qt to 5.14.0 on dec 23, no problems building devel  branch against that version.

**Comment by lbellonda** [comment]
Thank you, published a fix in 0.9.14.
