### ISSUE TITLE
QtScript deprecated since QT5.5

### ISSUE THREAD

**Issue by LW-archlinux** [lbellonda/qxmledit#66]
Hi, while building 0.9.14 in a clean chroot to verify if i had missed something I found that QtScript include files were missing.

I did find  a distro package for them, but also noticed QtScript was deprecated in 2015 with the Qt 5,5 release.
https://wiki.qt.io/New-Features-in-Qt-5.5#Deprecated_Functionality

Around the same time the last release of QT4 , 4.8.7 was pulbished.
https://www.qt.io/blog/2015/05/26/qt-4-8-7-released

Maybe it's time to deprecate qt4 and switch qxmledit to qt5 ?
If qxmledit is used on systems where qt5 is unavailable (enterprise OSes ?) maybe you could release 2 versions : one with qt4 support that will see maintenance only, and another that uses qt5  (and could support qt6 when it comes out).

**Comment by lbellonda** [comment]
Hello, dropping Qt4 support is not an option given the installed  base, and I prefer having only one version to support; however it is possible to be source compatible with both versions disabling some modules at compile time and gracefully degrading at run time.

I assign this issue as task for the next release.
I would like change the title of this issue to "QtScript deprecated since QT5.5"

**Comment by lbellonda** [comment]
References to QtScript have been removed in the "devel" branch. Could you confirm with clean compilation in your environment?

**Comment by LW-archlinux** [comment]
https://app.box.com/s/va95udg32kuuo9xomxaf4p1y33hzt3zt
https://app.box.com/s/qm015nwdo6wv8s3v3o2l3bl5cqnl8kt6

No issues building without QtScript present.

**Comment by frederickjh** [comment]
Removing the references to QtScript also fixes the issue with building Snaps on build.snapcraft.io. - frederickjh/qxmledit#17

**Comment by lbellonda** [comment]
Fixed in 0.9.15

**Comment by frederickjh** [comment]
The snap build locally after switching back to the master branch and release 0.9.15.  Currently building on Github so the 1,457 people on the stable channel on version 0.9.13 will soon be upgraded to the latest stable release.
