### ISSUE TITLE
Snap build failure

### ISSUE THREAD

**Issue by lbellonda** [lbellonda/qxmledit#69]
Branch:devel

Build failure details in issue: frederickjh/qxmledit#18

**Comment by frederickjh** [comment]
All of the five architectures have finished building QXmlEdit successfully on [build.snapcraft.io](https://build.snapcraft.io). The [QXmlEdit 0.9.15-Snapshot](https://snapcraft.io/qxmledit) build is available via the edge channel in the Snap Store.

@lbellonda  I have closed the issue on the QXmlEdit snap project, and you can close this issue too.
