### ISSUE TITLE
Error launching program

### ISSUE THREAD

**Issue by Kayzh3r** [lbellonda/qxmledit#70]
Hi all, 

First of all, thanks for your contribution to the community.

When I execute the .desktop file I get the following error:
KDEInit could not launch 'qxmledit':
Could not open library 'libkdeinit5_qxmledit'.
Cannot load library libkdeinit5_qxmledit: (libkdeinit5_qxmledit: cannot open shared object file: No such file or directory)

Kind regards

**Comment by lbellonda** [comment]
Hello, what operating system are you using? How QxmlEdit has been installed? Using what package manager?
Does it start via command line?

Thank you

**Comment by Kayzh3r** [comment]
Thanks for your fast answer.
I am using Kubuntu. I have installed QXmlEdit through qmake.
I tested the programs creating the project in Qt Creator and the program works perfectly so, I do not know what's happening.

Thanks so much

**Comment by Kayzh3r** [comment]
Also I added to the PATH environment variable the installation path folder of QXmlEdit and also created a .desktop file but the same error... Thanks again.

**Comment by lbellonda** [comment]
Hello, could you insert the full program path into the .desktop file? 
Can you send me the .desktop file you are using?

There is also a snap package for Ubuntu, but it is not maintained by me.
bye

**Comment by Kayzh3r** [comment]
Sorry for the delay in answering. The desktop file contains:
# .desktop entry for QXmlEdit
[Desktop Entry]
Type=Application
Name=QXmlEdit
Exec=/opt/qxmledit/qxmledit %u
Version=1.0
GenericName=Simple XML editor and XSD viewer.
NoDisplay=false
Comment=Edit XML files and view XSD documents.
Icon=/opt/qxmledit/qxmledit
Hidden=false
StartupNotify=true
#Path
Terminal=false
MimeType=text/xml;
Categories=Utility;Qt;Development;TextEditor;

**Comment by lbellonda** [comment]
Hello, a possible source of errors can be the location of the shared libraries. If you install from sources try to install them in a system shared folder, like /usr/lib64 or /usr/local/lib. 

Otherwise, you can modify the following line in the .desktop file
Exec=export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/qxmledit;/opt/qxmledit/qxmledit
and protect the /opt/qxmedit folder for unauthorized libraries writing.

**Comment by Kayzh3r** [comment]
Perfect!!! That's exactly the problem shared libraries. I thought that the first place for searching libraries was the path of the shell file but I was wrong. 

> protect the /opt/qxmedit folder for unauthorized libraries writing.

/opt/qxmedit is owned by root and only root has got write permissions is this enough?

Again thanks so much for your help.

**Comment by lbellonda** [comment]
>/opt/qxmedit is owned by root and only root has got write permissions is this enough?
I think yes, same of /usr/lib.

bye
