### ISSUE TITLE
libQxmlEdit* exec flag  in Linux

### ISSUE THREAD

**Issue by tieugene** [lbellonda/qxmledit#72]
Libfiles installed as executables

**Comment by lbellonda** [comment]
What kind of qt/sysop version are you using?
I am using qmake to generate makefiles.
Could you show me the permissions of other libraries derived from Qt applications?

Thank you.

**Comment by tieugene** [comment]
> What kind of qt/sysop version are you using?
Qt5 5.14.2, Fedora Linux 32 x64

> I am using qmake to generate makefiles.
Me too.
There is no another way here.

> Could you show me the permissions of other libraries derived from Qt applications?
Hmm...
I used many qt applications (starting from qt-based desktop environment LXQT).
But:
- most of them use cmake for building and have no permissions problems
- qmake-based have no shared libraries
As for qxmledit problem permissions set during "make install" stage.
libXmlEdit*.a files have right flags (0644).

**Comment by lbellonda** [comment]
I think that the installation template is built into qmake. It is possible to specify all the commands of the installation target in the .pro files, however I do not like change the .pro file with a feature that may be invalid in some qt version. I think that the best way to handle this problem is execute a post install script that change the permissions of the libraries before the packaging.
What do you think?

**Comment by tieugene** [comment]
> I think that the best way to handle this problem is execute a post install script that change the permissions of the libraries before the packaging.

I do this in may spec file (that used for packaging rpms).
But this seems dirty hack.

PS. I think the best way is to use cmake, that is more flexible for building process. But it is my own IMHO and no more.
Another big problem is [shared libs](https://github.com/lbellonda/qxmledit/issues/73) - this thing stops [my packaging qxmledit](https://bugzilla.redhat.com/show_bug.cgi?id=1845667) for official Fedora/CentOS repos.

**Comment by lbellonda** [comment]
Hello, the reason is that I would like to stick with vanilla Qt tools for compatibility reasons.

**Comment by tieugene** [comment]
This is not sources problem - this is Fedora build system tunes:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/ORKJTONHBKTC6U4HZSXOCX7LGRBDQYZR/
