### ISSUE TITLE
Wrong library versions

### ISSUE THREAD

**Issue by tieugene** [lbellonda/qxmledit#73]
Trying to build Fedora rpms, splitting insto subpackages (separate binary and library subpackages):
```
bash-5.0$ rpm -q --requires qxmledit-0.9.15-2.fc32.x86_64.rpm 
...
libQXmlEditSessions-0.9.15.so.0()(64bit)
libQXmlEditWidget-0.9.15.so.0()(64bit)

bash-5.0$ rpm -q --requires libqxmledit-devel-0.9.15-2.fc32.x86_64.rpm 
libQXmlEditSessions-0.9.15.so.0()(64bit)
libQXmlEditWidget-0.9.15.so.0()(64bit)

bash-5.0$ rpm -q --provides libqxmledit-0.9.15-2.fc32.x86_64.rpm 
libqxmledit = 0.9.15-2.fc32
libqxmledit(x86-64) = 0.9.15-2.fc32
```

**Comment by lbellonda** [comment]
Hello, I am not an expert in spec files, however I can help on it. May you share the spec and the rpms?

Thank you

**Comment by tieugene** [comment]
> May you share the spec and the rpms?

[No problem](https://tieugene.fedorapeople.org/rpms/qxmledit/).
This is not freshest version, but functionally is OK.
[Freshest rpms](https://koji.fedoraproject.org/koji/taskinfo?taskID=46249215).

**Comment by lbellonda** [comment]
I have not yet a Fedora environment to test. The SUSE package is slightly different and I can see that there are no naming differences in the SUSE packages.
You can enable the verbose output from rpmbuild and check the log. I think that the dependency of the application from libraries is automatically traced by rpmbuild and can be removed from spec.
Another possibility is to install only one package avoiding the devel includes; you can try.

**Comment by tieugene** [comment]
> The SUSE package is slightly different and I can see that there are no naming differences in the SUSE packages.

I can't find SUSE for 0.9.15 - just 0.9.10.
And they are "all-in-one" - binary and shared libs in one rpm.
This is not that I try to make.
Shared libs (if they are really must be shared) must be in separate package.
Or statically linked with binary (== not shared).

**Comment by lbellonda** [comment]
You can find SUSE spec here:
https://build.opensuse.org/package/view_file/editors/qxmledit/qxmledit.spec?expand=1

To ease testing I enclose:
- a fake QXmlEdit 0.9.15 that compiles very fast (yes, it is empty) , but has the same structure of the real one.
You can experiment locally without waiting for the full compilation.

[fake-qxmledit-0.9.15.zip](https://github.com/lbellonda/qxmledit/files/4872227/fake-qxmledit-0.9.15.zip)

Best regards

**Comment by tieugene** [comment]
> You can find SUSE spec here:
> https://build.opensuse.org/package/view_file/editors/qxmledit/qxmledit.spec?expand=1

This works at Fedora, thank you.
I will investigate this thing further.

PS. But anyway naming libraries like libQXmlEdit-0.9.15.so.0.9.15 is not good idea IMHO ($${QXMLEDIT_LIB_SUFFIX}).

**Comment by tieugene** [comment]
Dirty patch, that I use:
```diff
--- src/QXmlEdit.pro.orig	2020-07-05 16:48:24.793927681 +0300
+++ src/QXmlEdit.pro	2020-07-05 16:50:42.750346143 +0300
@@ -490,14 +490,14 @@
 else:win32:CONFIG(debug, debug|release): LIBS += -L$$OUT_PWD/../build/lib/debug/ -L$$OUT_PWD/../build -lQXmlEditWidget$${QXMLEDIT_LIB_SUFFIX}
 else:symbian: LIBS += -lQXmlEditWidget$${QXMLEDIT_LIB_SUFFIX}
 else:macx: LIBS += -L$(DESTDIR) -lQXmlEditWidget$${QXMLEDIT_LIB_SUFFIX}
-else:unix: LIBS += -L$$OUT_PWD/../build/ -lQXmlEditWidget$${QXMLEDIT_LIB_SUFFIX}
+else:unix: LIBS += -L$$OUT_PWD/../build/ -lQXmlEditWidget
 else:os2: LIBS += -L../build -lQXmlEdtW
 
 win32:CONFIG(release, debug|release): LIBS += -L$$OUT_PWD/../build/lib/release/ -L$$OUT_PWD/../build -lQXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
 else:win32:CONFIG(debug, debug|release): LIBS += -L$$OUT_PWD/../build/lib/debug/ -L$$OUT_PWD/../build -lQXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
 else:symbian: LIBS += -lQXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
 else:macx: LIBS += -L$(DESTDIR) -lQXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
-else:unix: LIBS += -L$$OUT_PWD/../build/ -lQXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
+else:unix: LIBS += -L$$OUT_PWD/../build/ -lQXmlEditSessions
 else:os2: LIBS += -L../build -lQXEdtSes
 
 equals(USE_QWTPLOT, "Y") {
--- src/QXmlEditWidget.pro.orig	2020-03-07 21:22:00.000000000 +0300
+++ src/QXmlEditWidget.pro	2020-07-05 16:51:32.277855390 +0300
@@ -54,7 +54,7 @@
   QT       += qml
 }
 
-TARGET = QXmlEditWidget$${QXMLEDIT_LIB_SUFFIX}
+TARGET = QXmlEditWidget
 os2:TARGET = QXmlEdtW
 TEMPLATE = lib
 
--- src/sessions/QXmlEditSessions.pro.orig	2020-03-07 21:22:00.000000000 +0300
+++ src/sessions/QXmlEditSessions.pro	2020-07-05 16:52:01.286153650 +0300
@@ -60,7 +60,7 @@
 }
 
 
-TARGET = QXmlEditSessions$${QXMLEDIT_LIB_SUFFIX}
+TARGET = QXmlEditSessions
 os2:TARGET = QXEdtSes
 TEMPLATE = lib
 
```

**Comment by lbellonda** [comment]
This issue has been addressed on "devel" branch (the base of next release) using command line parameters and defaults for versioning and suffixes.
A switch QXMLEDIT_USE_FAKE_SOURCES has been added to test in no time the outcome of the switches.
See INSTALL for details.
