### ISSUE TITLE
Closing last window does not quit

### ISSUE THREAD

**Issue by htgoebel** [lbellonda/qxmledit#78]
Contrary to most other application, when closing the last window, qxmledit does not quit

#### How to reproduce

* Start qxmledit
* Close the window by clicking the window*s "close" icon
* Check system tray ("dock")
→ qxmledit is still running

#### Expected behaviour

When closing the last window, the application should quit.

**Comment by lbellonda** [comment]
Hello, the program is resident and is accessible via tray icon. To quit immediately use the "Quit" menu item.

**Comment by lbellonda** [comment]
Hello, to enable this behavior, just de-select "Single instance application" in the Configuration panel in General tab.
