### ISSUE TITLE
Just FYI, the GPLv2 is not a EULA -- section 9 of GPL

### ISSUE THREAD

**Issue by torriem** [lbellonda/qxmledit#83]
I am a strong proponent of the GPL in general, and I'm glad to see it used by qxmledit.  However I note qxmledit requires me to agree to the GPL to simply use the program.  Why is this?  The GPL applies to developers and distribution primarily, not simple use of a binary. In fact, section 9 of the very text your license dialog presents says:

> 9. You are not required to accept this License, since you have not
> signed it.  However, nothing else grants you permission to modify or
> distribute the Library or its derivative works.  These actions are
> prohibited by law if you do not accept this License.  Therefore, by
> modifying or distributing the Library (or any work based on the
> Library), you indicate your acceptance of this License to do so, and
> all its terms and conditions for copying, distributing or modifying
> the Library or works based on it.

I've always appreciated this clause in the GPL. It's missed by most people.  The GPL governs distribution, not use.  The GPLv2 (or any subsequent version) is not a EULA.  If a user does not wish to accept the GPL, that's totally fine as long as they don't modify or distribute the source code to qxmledit.  Nothing prevents them from using qxmledit.  Reminding the users that qxmledit is released under the terms of the GPLv2 is just fine of course, but it bothers me when programs ask me to accept the GPL as it if were a EULA governing a program's mere use.

Don't worry, you're not the only one who's done this.  Even commercial programs that embed GPL'd executables sometimes require users to accept the GPL.

I know this all sounds horribly pedantic, but it's a huge pet peeve of mine and I think making the user think the GPL is a EULA contributes to the FUD that gets leveled against the GPL.

I do not expect this issue to be acted on. This is merely informational.  Anyone who wanted to fork qxmledit could remove the license dialog box if it bothered them enough.

**Comment by lbellonda** [comment]
The paragraph you cite is related to modifications and redistribution for developers, however you are right in stating that the user is free to use the program for any purpose. For this reason probably I will turn the license panel into an informative one.

**Comment by lbellonda** [comment]
On devel branch, for 0.9.18
